### ISSUE TITLE
Convert Vimeo links

### ISSUE THREAD

**Issue by sutty-coop** [link-rot-project/facing.life#1]
Profiles have embedded videos hosted on Vimeo, download and convert to local `<video>` tags

**Comment by sutty-coop** [comment]
There are 8 videos that `youtube-dl` can't download

https://vimeo.com/700606370
https://vimeo.com/700608746
https://vimeo.com/700610773
https://vimeo.com/700613549
https://vimeo.com/700614940
https://vimeo.com/700630743
https://vimeo.com/700631406
https://vimeo.com/700631548

**Comment by sutty-coop** [comment]
@walkerlj0 @brandontauszik Sadly I hit the github per-repository quota while uploading videos:

> This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Turns out there's a 1GB limit on LFS storage for free repositories:

https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage

But disabling LFS is not an option, since they block uploads bigger than 100MB:

https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github

Options would be:

* Acquiring a data plan or moving this repository to a paid Github account
* Host videos separately, on an IPFS provider.  If you have your own IPFS nodes or were planning to use that, we can send the files directly to them
* Keep vimeo embedded videos for now

**Comment by brandontauszik** [comment]
Hmm well my vimeo plan is premium currently, but will still work if I stop paying and it becomes a free account.... it would seem to be an archivability weak point but maybe not ...? that way we wouldn;t need custom players built etc.

**Comment by sutty-coop** [comment]
Thanks! @walkerlj0 what do you think?

**Comment by walkerlj0** [comment]
@sutty-coop we decided that we will embed the Vimeo videos, but also create backups pinned on IPFS. We can put the link in the alt text perhaps?

**Comment by walkerlj0** [comment]
For the time being, we decided to continue to host on Vimeo
