### ISSUE TITLE
Facing Life Favicon

### ISSUE THREAD

**Issue by brandontauszik** [link-rot-project/facing.life#10]
the site currently doesn't have one. please pull the pulitzer center favicon and use that.

<img width="695" alt="Screenshot 2023-09-13 at 12 23 16 PM" src="https://github.com/link-rot-project/facing.life/assets/141079987/b67b704a-b83f-4ed0-9a7f-4ec4e3f4c944">

**Comment by sutty-coop** [comment]
Done!

**Comment by walkerlj0** [comment]
Resolved, new favicon is up!
