### ISSUE TITLE
Publish website on Distributed Press

### ISSUE THREAD

**Issue by sutty-coop** [link-rot-project/facing.life#11]
Steps:

1. [Remove repository and add it again](https://docs.github.com/en/repositories/working-with-files/managing-large-files/removing-files-from-git-large-file-storage#git-lfs-objects-in-your-repository) to reset the storage quota for this organization.
2. Obtain a Distributed Press publisher token for Linkrot (already asked for one).
3. Recreate the repository and configure the token as an Action Secret
4. Set DNS information #7

**Comment by sutty-coop** [comment]
@walkerlj0 the latest changes are on the test site, but we can't push them here because of the storage quota.  I found we have to remove the repository and recreate it to reset the quota.

**Comment by benhylau** [comment]
@sutty-coop can you publish this to Distributed Press and make these testing links for review?

- https://facing-life.testing.sutty.nl
- ipns://facing-life.testing.sutty.nl
- hyper://facing-life.testing.sutty.nl

Thanks.

**Comment by sutty-coop** [comment]
You can test those links using Agregore :)

Also through gateways at:

https://facing--life-testing-sutty-nl.hyper.hypha.coop/

https://facing--life-testing-sutty-nl.ipns.ipfs.hypha.coop/

**Comment by fauno** [comment]
ipns://facing.life
hyper://facing.life
https://facing-life.hyper.hypha.coop/
https://facing-life.ipns.ipfs.hypha.coop/

**Comment by fauno** [comment]
If everything's good with this publication, I'll remove this repository and re upload it.  Issues were archived at a mirror I made on gitlab.com.

@walkerlj0 please close the issue to let me know

**Comment by walkerlj0** [comment]
This site looks goood!
