### ISSUE TITLE
no click and drag

### ISSUE THREAD

**Issue by walkerlj0** [link-rot-project/facing.life#14]
<img width="1285" alt="Screenshot 2023-10-25 at 2 32 33 PM" src="https://github.com/link-rot-project/facing.life/assets/66978602/210a3305-d2d5-4192-8e4c-08fb06253e8c">
Make it so you cannot click and drag the icons in the bottomw

**Comment by fauno** [comment]
Done, you may need to force reload the site to re-download the js file

**Comment by walkerlj0** [comment]
Resolved/ working as intended
