### ISSUE TITLE
Make sure all images on all pages have a 4:5 ratio

### ISSUE THREAD

**Issue by walkerlj0** [link-rot-project/facing.life#16]
<img width="1353" alt="Screenshot 2023-10-25 at 2 34 27 PM" src="https://github.com/link-rot-project/facing.life/assets/66978602/a1da6d94-5e76-4390-adc0-f0c715f8643d">

All images should have a ration of height : width is 4:5

**Comment by fauno** [comment]
Done: https://www.facing.life/fahim/

**Comment by walkerlj0** [comment]
Checked with Brandon, Fahim's is fixes
