### ISSUE TITLE
Footer showing up in middle of screen on mobile

### ISSUE THREAD

**Issue by walkerlj0** [link-rot-project/facing.life#17]
The scrolling footer shows up in the middle of screen on mobile. See screenshot
![Screenshot_20231102-073654.png](https://github.com/link-rot-project/facing.life/assets/66978602/8442da6b-1b58-4748-991b-e310c2d7a3d0)

**Comment by fauno** [comment]
I think it's designed like that? Could you confirm @brandontauszik ?

**Comment by fauno** [comment]
Done, it can be reviewed at https://facing-life.testing.sutty.nl/

**Comment by walkerlj0** [comment]
Looks good thank you!
