### ISSUE TITLE
Create a place to drop Video FIles

### ISSUE THREAD

**Issue by walkerlj0** [link-rot-project/facing.life#4]
@sutty-coop, Brandon has copies of all these video files. Apparently there may be some issues with the 360 files

**Comment by sutty-coop** [comment]
If Brandon uploads them to IPFS we can download them locally and they'll be deduplicated later by IPFS itself when we host the site on DPress

**Comment by walkerlj0** [comment]
we decided on using a Google Drive, try this one here: https://drive.google.com/drive/folders/1Hbo4gVwloygqjfL5ZQuXlRt-bl_NXWkR

We will add suttyweb@gmail for access, let us know if we should add anyone else @sutty-coop
