### ISSUE TITLE
Make sure 360 video embeds work

### ISSUE THREAD

**Issue by walkerlj0** [link-rot-project/facing.life#5]
There are some videos that you can interact with (click and drag) to view a video in 360 degrees. See example here: [https://facing-life.testing.sutty.nl/travielle/](https://facing-life.testing.sutty.nl/travielle/) (Titiled Gaming with Travielle)

**Comment by walkerlj0** [comment]
See uploaded files in this drive: https://drive.google.com/drive/folders/1Hbo4gVwloygqjfL5ZQuXlRt-bl_NXWkR

**Comment by sutty-coop** [comment]
Maybe we can test with something like this @brandontauszik ?  (See examples on the profile link)

https://github.com/videojs/videojs-vr

**Comment by brandontauszik** [comment]
Not sure what that is

**Comment by brandontauszik** [comment]
Wow cool they built their own 360 player? Very cool. Seems to work even on mobile? What options do you have? Need fullscreen button (which I don't see) and ability to add custom thumbnail.

**Comment by sutty-coop** [comment]
I'm not sure about custom thumbnail but there's a full screen button, I just tested it on my Android phone.  Is the custom thumbnail a hard requirement?

**Comment by brandontauszik** [comment]
Yes, they all have decription titles and a 360 icon so folks know what to do 

<img width="1224" alt="Screenshot 2023-08-18 at 12 43 59 PM" src="https://github.com/link-rot-project/facing.life/assets/141079987/0db32d24-7170-4ca1-868e-5d45adc54d38">

**Comment by sutty-coop** [comment]
It seems to add its own icon, but I can run some tests and see if it actually supports the poster.  But it's related to what we decide on #1 

![image](https://github.com/link-rot-project/facing.life/assets/113475467/38fe4ef6-6ffd-4777-b9b1-3cbf1a61d77d)

**Comment by brandontauszik** [comment]
Sounds good, will stand by.

**Comment by walkerlj0** [comment]
360 embeds are working
