### ISSUE TITLE
Image Aspect Ratio

### ISSUE THREAD

**Issue by walkerlj0** [link-rot-project/facing.life#9]
The aspect ration should be 4:5 (height:width) for all (?) images on the Facing Life page

There are two solutions

1) @brandontauszik can see if it's possible to update that change in wordpress. We should explore this first. We think that this was changed once the parallax scrolling issue was addressed with the plugin update.
2) If it's not possible to change that quickly in wordpress, is it possible for @sutty-coop to modify the CSS in the static site here to set all images to have a 4:5 ratio

**Comment by walkerlj0** [comment]
@brandontauszik is it possible to make this change in wordpress?

**Comment by brandontauszik** [comment]
I’m going to hit up my Wordpress dev on Upwork to resolve.On Sep 5, 2023, at 11:16 AM, Lindsay Walker ***@***.***> wrote:﻿
@brandontauszik is it possible to make this change in wordpress?

**Comment by sutty-coop** [comment]
Hi, we just recovered them from history, since we had a previous working version.  Apparently during the upgrade the aspect-ratio definitions were reset to 1:1.

https://facing-life.testing.sutty.nl/

**Comment by walkerlj0** [comment]
<img width="684" alt="Screenshot 2023-09-15 at 3 12 31 PM" src="https://github.com/link-rot-project/facing.life/assets/66978602/925649d2-3ae5-41ba-b652-a7b282965c8b">
Updated
